version: '3.4'
services:
  jira:
    image: haxqer/jira
    container_name: jira-srv
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./jira:/var/jira
    networks:
      - jiranetwork
#    environment:
#      - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=1024m
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql-jira
    environment:
      - MYSQL_DATABASE=jira 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=123123
      - TZ='Asia/Shanghai'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - jiranetwork

networks:
  jiranetwork:
    driver: bridge
